Controllers/TallaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WatchMaker.Models;

namespace WatchMaker.Controllers
{
    [Autenticado]
    public class TallaController : Controller
    {
        // GET: Talla
        public ActionResult Index()
        {
            string nombreUsuario = HttpContext.User.Identity.Name;
            ViewBag.NombreUsuario = nombreUsuario;
            using (DbModels context = new DbModels())
            {
                return View(context.Tallas.ToList());
            }
        }

        // GET: Talla/Details/5
        public ActionResult Details(int id)
        {
            string nombreUsuario = HttpContext.User.Identity.Name;
            ViewBag.NombreUsuario = nombreUsuario;

            using (DbModels context = new DbModels())
            {
                return View(context.Tallas.Where(x => x.idtalla == id).FirstOrDefault());
            }
        }

        // GET: Talla/Create
        public ActionResult Create()
        {
            string nombreUsuario = HttpContext.User.Identity.Name;
            ViewBag.NombreUsuario = nombreUsuario;
            return View();
        }

        // POST: Talla/Create
        [HttpPost]
        public ActionResult Create(Tallas tallas)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.Tallas.Add(tallas);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Talla/Edit/5
        public ActionResult Edit(int id)
        {
            using (DbModels context = new DbModels())
            {

                return View(context.Tallas.Where(x => x.idtalla == id).FirstOrDefault());

            }
        }

        // POST: Talla/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Tallas tallas)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.Entry(tallas).State = System.Data.Entity.EntityState.Modified;
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Talla/Delete/5
        public ActionResult Delete(int id)
        {
            string nombreUsuario = HttpContext.User.Identity.Name;
            ViewBag.NombreUsuario = nombreUsuario;
            using (DbModels context = new DbModels())
            {
                return View(context.Tallas.Where(x => x.idtalla == id).FirstOrDefault());
            }
        }

        // POST: Talla/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    Tallas tallas = context.Tallas.Where(x => x.idtalla == id).FirstOrDefault();
                    context.Tallas.Remove(tallas);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    <!-- Cargar Bootstrap 5 sin Popper.js -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEJZKXhqz5Dd1zZzdTST7tUve1gu3yq83l4rJzAQ2UBf5t3W06hbP6KJ0W4t6" crossorigin="anonymous">

    <!-- Cargar el script de Bootstrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>



    <link href="~/Content/EstiloArticuloboto.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home", new { area = "" })" class="navbar-brand d-flex align-items-center">
                    <img src="~/Content/Imagenes/Icono.jpg" alt="Watchmaker Icon" style="height: 20px; margin-right: 5px;">

                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Usuario", "Index", "Usuario")</li>
                    <li>@Html.ActionLink("Bodega", "Index", "Articulo")</li>
                    <li>@Html.ActionLink("Categoria", "Index", "Categoria")</li>
                    <li>@Html.ActionLink("TipoArticulo", "Index", "TipoMaterial")</li>
                    <li>@Html.ActionLink("Material", "Index", "Material")</li>
                    <li>@Html.ActionLink("Tallas", "Index", "Talla")</li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">
                        @if (ViewBag.NombreUsuario != null)
                        {
                            <span>Bienvenido, @ViewBag.NombreUsuario</span>
                        }
                    </li>
                    <li>
                        @Html.ActionLink("Cerrar Sesión", "Logout", "CloseSesion", null, new { @class = "btn btn-danger navbar-btn", style = "height: 30px; line-height: 30px; padding: 0 10px; color:white; " })
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplicacion WATCHMAKER</p>
            <p>Derechos Reservados </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/Js/Imprimir.js"></script>
    <script src="~/Content/Js/imprimirar.js"></script>
    <script src="~/Content/Js/buscarar.js"></script>
    <script src="~/Content/Js/MostrarImagen.js"></script>
    <script src="~/Content/Js/BuscarImagen.js"></script>
    <script src="~/Content/Js/Exportardatos.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.2/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.9/xlsx.full.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>